services:
  recall:    # recall is now a service, builds image on my own
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - ollama

  ollama:     # ollama is also a service, gets the image from the docker hub, this is the reason why ollama:11434 is supported, it could also be named banana and then it would be banana:11434
    image: ollama/ollama   # not an official img, but published by ollama themselves.